spring:
  application:
    name: cap-backend
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/capstone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

